### ISSUE TITLE
Target to ES6

### ISSUE THREAD

**Issue by mbalex99** [joaogarin/angular2-electron#5]
Electron is ES6, so we should probably remove es6-shim and change the target in the `tsconfig.json` to `es6`

**Comment by joaogarin** [comment]
Yeah that makes sense. I will try to do a PR today for this. Will keep the issue updated on that ;O tks

**Comment by mbalex99** [comment]
I think we can also remove `core-js` as well.

**Comment by joaogarin** [comment]
I think core-js will still be necessary for es7-reflect feature. I dont think thats implemented in any browser yet. Altough I am not entirely sure https://github.com/zloirock/core-js/issues/152

**Comment by joaogarin** [comment]
I dont think you can target ES6 actually with electron, and the reason is that  ES6 modules are not yet implemented in any browser as far as I know..So I dont think this would be an option but I am trying to dig into that. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import

**Comment by joaogarin** [comment]
I think I will close this one, as far as I can tell and from all the repos I found (including the official angular one altough still on beta.2) they all target es5, and I am pretty sure the reason is ES6 modules.

let me know if you find something else, or have some ideas on this. Feel free to reopen if you think there is something to be done still.
