### ISSUE TITLE
Clean project

### ISSUE THREAD

**Issue by divanvb** [joaogarin/angular2-electron#8]
Hey man hope you're doing well.
Want to know if maybe you can create something that would basically be a clean project with Angular 2 and material2 without oauth etc. Just the bare basics with maybe a started page just saying hello world and then having it do the same compiling and structuring like it is currently doing?

**Comment by joaogarin** [comment]
Hello,

Sorry but that's really not the purpose here..I try to make this as clean as possible but still try and provide something kind of useful depending on what people find interesting. auth with electron is something kind of unique since you need to handle the popup in the different process so I think thats something I want to keep.

You can easily take out the auth part just by taking out the login component and the service.

Best regards

**Comment by divanvb** [comment]
Cool thanks man, I'll play around with it and try and develop on my own with integrating the oauth as an option when creating the project along with a few other things if thats cool with you?
